name: Interactive Games

on:
  issues:
    types: [opened]

jobs:
  tictactoe:
    name: Tic-Tac-Toe Game
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'tictactoe|')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Play Tic-Tac-Toe
        uses: timburgan/timburgan@master
        with:
          game: tictactoe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rps:
    name: Rock Paper Scissors
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'rps|')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Play RPS
        uses: timburgan/timburgan@master
        with:
          game: rps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  guess:
    name: Guess the Number
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'guess|')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Play Guess Game
        uses: timburgan/timburgan@master
        with:
          game: guess
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
